### ISSUE TITLE
URLのチェックが行われない点+α

### ISSUE THREAD

**Issue by shiv3** [ahaha0807/bookmark_binder#5]
- url形式でないものまでリンクが生成されてしまう
- 出来ればhttp://がなくても自動で判別すれば尚良い気がする
- タイトルに&<>などの文字が使えない
- URL部分に`javascript:~~`で任意のスクリプトが実行可能なリンクが生成/import可能(xssの脆弱性)
  ![2016-07-18 1 11 01](https://cloud.githubusercontent.com/assets/9666625/16901646/b6203284-4c84-11e6-84dc-8b34a19bb0a1.png)

**Comment by gatchan0807** [comment]
ありがとうございます！！
`javascript:~~`でスクリプト使えるの知りませんでした…ｗ
